package cli

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"reflect"

	"github.com/blaxel-ai/toolkit/cli/core"
	"github.com/blaxel-ai/toolkit/sdk"
	"github.com/spf13/cobra"
)

func init() {
	core.RegisterCommand("apply", func() *cobra.Command {
		return ApplyCmd()
	})
}

type ResourceOperationResult struct {
	Status    string
	UploadURL string
}

type ApplyResult struct {
	Kind   string
	Name   string
	Result ResourceOperationResult
}

// ApplyOption defines a function type for apply options
type ApplyOption func(*applyOptions)

// applyOptions holds all possible options for Apply
type applyOptions struct {
	recursive bool
}

// WithRecursive sets the recursive option
func WithRecursive(recursive bool) ApplyOption {
	return func(o *applyOptions) {
		o.recursive = recursive
	}
}

func ApplyCmd() *cobra.Command {
	var filePath string
	var recursive bool
	var envFiles []string
	var commandSecrets []string
	cmd := &cobra.Command{
		Use:   "apply",
		Short: "Apply a configuration to a resource by file",
		Long:  "Apply a configuration to a resource by file",
		Example: `
			bl apply -f ./my-deployment.yaml
			# Or using stdin
			cat file.yaml | bl apply -f -
		`,
		Run: func(cmd *cobra.Command, args []string) {
			core.LoadCommandSecrets(commandSecrets)
			core.ReadSecrets("", envFiles)
			_, err := Apply(filePath, WithRecursive(recursive))
			if err != nil {
				core.PrintError("Apply", err)
				os.Exit(1)
			}
		},
	}

	cmd.Flags().StringVarP(&filePath, "filename", "f", "", "Path to YAML file to apply")
	cmd.Flags().BoolVarP(&recursive, "recursive", "R", false, "Process the directory used in -f, --filename recursively. Useful when you want to manage related manifests organized within the same directory.")
	cmd.Flags().StringSliceVarP(&envFiles, "env-file", "e", []string{".env"}, "Environment file to load")
	cmd.Flags().StringSliceVarP(&commandSecrets, "secrets", "s", []string{}, "Secrets to deploy")
	err := cmd.MarkFlagRequired("filename")
	if err != nil {
		core.PrintError("Apply", err)
		os.Exit(1)
	}

	return cmd
}

func ApplyResources(results []core.Result) ([]ApplyResult, error) {
	applyResults := []ApplyResult{}
	resources := core.GetResources()

	// À ce stade, results contient tous vos documents YAML
	for _, result := range results {
		for _, resource := range resources {
			if resource.Kind == result.Kind {
				name := result.Metadata.(map[string]interface{})["name"].(string)
				resultOp := PutFn(resource, result.Kind, name, result)
				if resultOp != nil {
					applyResults = append(applyResults, ApplyResult{
						Kind:   resource.Kind,
						Name:   name,
						Result: *resultOp,
					})
				}
			}
		}
	}
	return applyResults, nil
}

func Apply(filePath string, opts ...ApplyOption) ([]ApplyResult, error) {
	// Default options
	options := &applyOptions{
		recursive: false,
	}

	// Apply all provided options
	for _, opt := range opts {
		opt(options)
	}

	results, err := core.GetResults("apply", filePath, options.recursive)
	if err != nil {
		return nil, fmt.Errorf("error getting results: %w", err)
	}

	applyResults, err := ApplyResources(results)
	if err != nil {
		return nil, fmt.Errorf("error applying resources: %w", err)
	}

	return applyResults, nil
}

// Helper function to handle common resource operations
func handleResourceOperation(resource *core.Resource, name string, resourceObject interface{}, operation string) (*http.Response, error) {
	ctx := context.Background()

	// Get the appropriate function based on operation
	var fn reflect.Value
	if operation == "put" {
		fn = reflect.ValueOf(resource.Put)
	} else {
		fn = reflect.ValueOf(resource.Post)
	}

	if fn.Kind() != reflect.Func {
		return nil, fmt.Errorf("fn is not a valid function")
	}

	type LabelsRetriever struct {
		Metadata struct {
			Labels map[string]string `json:"labels"`
		} `json:"metadata"`
	}

	autogeneratedInLabels := false

	resourceJson, _ := json.Marshal(resourceObject)
	labelsRetriever := LabelsRetriever{}
	err := json.Unmarshal(resourceJson, &labelsRetriever)
	if err == nil {
		autogeneratedInLabels = labelsRetriever.Metadata.Labels["x-blaxel-auto-generated"] == "true"
	}

	// Handle spec conversion
	specJson, err := json.Marshal(resourceObject)
	if err != nil {
		return nil, fmt.Errorf("error marshaling spec: %v", err)
	}

	destBody := reflect.New(resource.SpecType).Interface()
	if err := json.Unmarshal(specJson, destBody); err != nil {
		return nil, fmt.Errorf("error unmarshaling to target type: %v", err)
	}

	// Call the function
	var results []reflect.Value
	var opts sdk.RequestEditorFn

	if autogeneratedInLabels {
		opts = sdk.RequestEditorFn(func(ctx context.Context, req *http.Request) error {
			q := req.URL.Query()
			q.Add("upload", "true")
			req.URL.RawQuery = q.Encode()
			return nil
		})
	}
	switch operation {
	case "put":
		values := []reflect.Value{
			reflect.ValueOf(ctx),
			reflect.ValueOf(name),
			reflect.ValueOf(destBody).Elem(),
		}
		if opts != nil {
			values = append(values, reflect.ValueOf(opts))
		}
		results = fn.Call(values)
	case "post":
		values := []reflect.Value{
			reflect.ValueOf(ctx),
			reflect.ValueOf(destBody).Elem(),
		}
		if opts != nil {
			values = append(values, reflect.ValueOf(opts))
		}
		results = fn.Call(values)
	default:
		return nil, fmt.Errorf("invalid operation: %s", operation)
	}

	if len(results) <= 1 {
		return nil, nil
	}

	if err, ok := results[1].Interface().(error); ok && err != nil {
		return nil, err
	}

	response, ok := results[0].Interface().(*http.Response)
	if !ok {
		return nil, fmt.Errorf("the result is not a pointer to http.Response")
	}

	return response, nil
}

func PutFn(resource *core.Resource, resourceName string, name string, resourceObject interface{}) *ResourceOperationResult {
	failedResponse := ResourceOperationResult{
		Status: "failed",
	}
	if resource.Kind == "IntegrationConnection" {
		client := core.GetClient()
		response, err := client.GetIntegrationConnectionWithResponse(context.Background(), name)
		if err == nil && response.StatusCode() == 200 {
			editUrl := fmt.Sprintf("%s/%s/workspace/settings/integrations/%s", core.GetAppURL(), core.GetWorkspace(), *response.JSON200.Spec.Integration)
			fmt.Printf("Resource %s:%s already exists, skipping update\nTo edit, go to %s\n", resourceName, name, editUrl)
			return &ResourceOperationResult{
				Status: "skipped",
			}
		}
	}
	formattedError := fmt.Sprintf("Resource %s:%s error: ", resourceName, name)
	response, err := handleResourceOperation(resource, name, resourceObject, "put")
	if err != nil {
		fmt.Printf("%s%v", formattedError, err)
		return &failedResponse
	}
	if response == nil {
		return nil
	}

	defer func() { _ = response.Body.Close() }()
	var buf bytes.Buffer
	if _, err := io.Copy(&buf, response.Body); err != nil {
		fmt.Printf("%s%v", formattedError, err)
		return &failedResponse
	}

	if response.StatusCode == 404 {
		// Need to create the resource
		return PostFn(resource, resourceName, name, resourceObject)
	}

	if response.StatusCode >= 400 {
		fmt.Printf("Resource %s:%s error: %s\n", resourceName, name, buf.String())
		os.Exit(1)
		return &failedResponse
	}

	var res interface{}
	if err := json.Unmarshal(buf.Bytes(), &res); err != nil {
		fmt.Printf("%s%v", formattedError, err)
		return &failedResponse
	}
	result := ResourceOperationResult{
		Status: "configured",
	}
	if uploadUrl := response.Header.Get("X-Blaxel-Upload-Url"); uploadUrl != "" {
		result.UploadURL = uploadUrl
	}
	fmt.Printf("Resource %s:%s configured\n", resourceName, name)
	return &result
}

func PostFn(resource *core.Resource, resourceName string, name string, resourceObject interface{}) *ResourceOperationResult {
	failedResponse := ResourceOperationResult{
		Status: "failed",
	}
	formattedError := fmt.Sprintf("Resource %s:%s error: ", resourceName, name)
	response, err := handleResourceOperation(resource, name, resourceObject, "post")
	if err != nil {
		fmt.Printf("%s%v\n", formattedError, err)
		return &failedResponse
	}
	if response == nil {
		return &failedResponse
	}

	defer func() { _ = response.Body.Close() }()
	var buf bytes.Buffer
	if _, err := io.Copy(&buf, response.Body); err != nil {
		fmt.Printf("%s%v\n", formattedError, err)
		return &failedResponse
	}

	if response.StatusCode >= 400 {
		fmt.Printf("Resource %s:%s error: %s\n", resourceName, name, buf.String())
		os.Exit(1)
		return &failedResponse
	}

	var res interface{}
	if err := json.Unmarshal(buf.Bytes(), &res); err != nil {
		fmt.Printf("%s%v\n", formattedError, err)
		return &failedResponse
	}
	result := ResourceOperationResult{
		Status: "created",
	}
	if uploadUrl := response.Header.Get("X-Blaxel-Upload-Url"); uploadUrl != "" {
		result.UploadURL = uploadUrl
	}
	fmt.Printf("Resource %s:%s created\n", resourceName, name)
	return &result
}
