package cli

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/blaxel-ai/toolkit/cli/core"
)

// deployNoBuildGrace bounds how long --wait waits for the build pipeline to
// react to an upload. Every submission that builds is answered within seconds
// by a build event (started, failed, or an identical build reused). A variable
// so tests can shorten it.
var deployNoBuildGrace = 3 * time.Minute

// deployFinalGrace bounds how long --wait holds a DEPLOYED resource for the
// platform's final "deployment.succeeded" event, which came 5 to 115 seconds
// after it in practice. A variable so tests can shorten it.
var deployFinalGrace = time.Minute

// deployObservation is local to this invocation, not the resource's history.
type deployObservation struct {
	kind, name    string
	autoGenerated bool
	baseline      rolloutBaseline
	// baselineEvents are the events the resource had before the apply, or nil
	// when unreadable; any other event is new.
	baselineEvents map[failureEvent]struct{}
	initialStatus  string
	started        time.Time
	rollout        resourceRollout
	sawRollout     bool
	done           bool
	err            error
	diagnostics    *deployDiagnostics
	// reusedAt is set when the platform answered this submission by reusing an
	// identical image build, in which case no new revision follows.
	reusedAt time.Time
	// noBuild is set when no build event followed the upload in time.
	noBuild bool
	// notice is a clear, successful, non-default outcome worth reporting.
	notice string
	// settleBy is when to stop holding a DEPLOYED resource for the final event.
	settleBy time.Time
}

func needsDeployMonitoring(kind string) bool {
	switch strings.ToLower(kind) {
	case "agent", "function", "job", "sandbox", "application":
		return true
	}
	return false
}

// applyNonInteractive submits the deployment. Without wait it returns once the
// code is submitted, exactly as a plain `bl deploy --yes` always has. With wait
// it also follows this submission's build and rollout to a verdict.
func (d *Deployment) applyNonInteractive(wait bool) error {
	d.wait = wait
	if !wait {
		return d.Apply()
	}

	for _, manifest := range d.blaxelDeployments {
		kind := strings.ToLower(manifest.Kind)
		metadata, _ := manifest.Metadata.(map[string]interface{})
		name, _ := metadata["name"].(string)
		if !needsDeployMonitoring(kind) || name == "" {
			continue
		}
		observation := deployObservation{kind: kind, name: name}
		if labels, ok := metadata["labels"].(map[string]interface{}); ok {
			observation.autoGenerated = labels["x-blaxel-auto-generated"] == "true" || labels["x-blaxel-auto-generated"] == true
		}
		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		rollout, err := getResourceRolloutContext(ctx, kind, name)
		cancel()
		if err == nil {
			observation.initialStatus = rollout.Status
			observation.baseline = rolloutBaseline{revision: rollout.LatestRevision, deployedRevision: rollout.DeployedRevision, known: true}
			var events []failureEvent
			if json.Unmarshal(rollout.Events, &events) == nil {
				observation.baselineEvents = make(map[failureEvent]struct{}, len(events))
				for _, e := range events {
					observation.baselineEvents[e] = struct{}{}
				}
			}
		}
		// Capture time immediately before applying, after the baseline read.
		observation.started = time.Now()
		d.observations = append(d.observations, observation)
	}
	if err := d.Apply(); err != nil {
		d.observations = nil // nothing to wait for: report a plain submission error
		return err
	}

	timeout := d.timeout
	if timeout <= 0 {
		timeout = time.Hour
	}
	ctx, cancel := context.WithTimeout(context.Background(), timeout)
	defer cancel()
	return d.waitForRollouts(ctx, 3*time.Second)
}

// Poll all resources under one monitoring deadline. API calls inherit it, so a
// slow read cannot silently extend --timeout. Upload/apply retain their existing
// behavior; as in the TUI, --timeout covers build and rollout monitoring.
func (d *Deployment) waitForRollouts(ctx context.Context, interval time.Duration) error {
	ticker := time.NewTicker(interval)
	defer ticker.Stop()
	waitStart := time.Now()
	for {
		pending := false
		for i := range d.observations {
			o := &d.observations[i]
			if o.done {
				continue
			}
			if ctx.Err() != nil {
				o.done = true
				o.err = core.MarkExpectedError(fmt.Errorf("deployment timed out waiting for %s/%s", o.kind, o.name), core.CLIErrorOperational)
				o.diagnostics = d.failureDiagnostics(*o, "DEPLOY_TIMEOUT")
				continue
			}
			rollout, err := getResourceRolloutContext(ctx, o.kind, o.name)
			if err == nil {
				o.rollout = rollout
				o.observeReusedBuild()
				switch rollout.Status {
				case "BUILDING", "DEPLOYING":
					o.sawRollout = true
				case "DEPLOYED":
					if !o.reusedAt.IsZero() {
						o.done = o.deployedSinceReuse()
					} else {
						o.done = deployedStatusIsFinal(o.autoGenerated, o.sawRollout, o.baseline, rollout.DeployedRevision)
					}
					// DEPLOYED is reported once one cluster is ready. The rollout is
					// finished at the platform's "deployment.succeeded" event, and an
					// update submitted before it can be silently dropped, so hold for
					// it, but not for long.
					if o.done && o.rolloutInProgress() {
						if o.settleBy.IsZero() {
							o.settleBy = time.Now().Add(deployFinalGrace)
						}
						o.done = time.Now().After(o.settleBy)
					}
					if o.done {
						o.notice = o.reusedNotice()
					}
				case "FAILED":
					if o.failureIsCurrent() {
						o.done = true
						o.diagnostics = d.failureDiagnostics(*o, "")
						o.err = core.MarkExpectedError(failureError("resource deployment failed", o.diagnostics.Cause), core.CLIErrorOperational)
					}
				case "DEACTIVATED", "DEACTIVATING", "DELETING":
					o.done = true
					o.err = core.MarkExpectedError(fmt.Errorf("resource is being deactivated or deleted"), core.CLIErrorOperational)
					o.diagnostics = d.failureDiagnostics(*o, "ROLLOUT_FAILED")
				}
				if !o.done && o.buildNotPickedUp(time.Since(waitStart)) {
					o.done, o.noBuild = true, true
					o.err = core.MarkExpectedError(fmt.Errorf("no build started for %s/%s after the upload", o.kind, o.name), core.CLIErrorOperational)
					o.diagnostics = d.failureDiagnostics(*o, "DEPLOY_TIMEOUT")
				}
			}
			pending = pending || !o.done
		}
		if !pending {
			for _, o := range d.observations {
				if o.err != nil {
					return o.err
				}
			}
			return nil
		}
		select {
		case <-ctx.Done():
			// Mark every pending resource with timeout, preserving its last status.
		case <-ticker.C:
		}
	}
}

func (o deployObservation) failureIsCurrent() bool {
	event, ok := latestFailureEvent(o.rollout.Events, "")
	if !ok {
		// Without usable events, retain the TUI's stale-FAILED grace period, but
		// never borrow a cause from an older event.
		return o.initialStatus != "FAILED" || o.sawRollout || time.Since(o.started) >= 15*time.Second
	}
	if !strings.EqualFold(event.Status, "failed") && !strings.HasSuffix(event.Type, ".failed") {
		return false
	}
	if o.baselineEvents != nil {
		// Events seen before the apply are old; this machine's clock is not used.
		if _, old := o.baselineEvents[event]; old {
			return false
		}
		// The platform re-applied an existing revision for this submission, so a
		// failure of that revision is this deploy's failure.
		if !o.reusedAt.IsZero() {
			return true
		}
	} else if timestamp, err := time.Parse(time.RFC3339Nano, event.Time); err != nil || timestamp.Before(o.started) {
		return false
	}
	return event.Revision == "" || !o.baseline.known || !o.baseline.includes(event.Revision)
}

// newEvents returns the events emitted since the apply, and false when they
// cannot be told apart from older ones. Comparing events rather than clocks
// keeps this independent of this machine's time.
func (o deployObservation) newEvents() ([]failureEvent, bool) {
	var events, fresh []failureEvent
	if o.baselineEvents == nil || json.Unmarshal(o.rollout.Events, &events) != nil {
		return nil, false
	}
	for _, e := range events {
		if _, old := o.baselineEvents[e]; !old {
			fresh = append(fresh, e)
		}
	}
	return fresh, true
}

func isBuildEvent(e failureEvent) bool { return strings.Contains(e.Type, ".buildimage.") }

// observeReusedBuild records the platform's answer to a submission whose source
// is identical to an earlier build: the image is reused, no build runs, and the
// current revision is re-applied instead of a new one being created. Without a
// readable baseline it concludes nothing and the wait falls back to the
// revision rule and, at worst, a timeout that names this case.
func (o *deployObservation) observeReusedBuild() {
	events, _ := o.newEvents()
	for _, e := range events {
		if !o.reusedAt.IsZero() || !strings.HasSuffix(e.Type, ".buildimage.succeeded") || !strings.Contains(strings.ToLower(e.Message), "identical image") {
			continue
		}
		if at, err := time.Parse(time.RFC3339Nano, e.Time); err == nil {
			o.reusedAt = at
		}
	}
}

// deployedSinceReuse reports a DEPLOYED event that is new since this apply and
// later than the reuse event, so a previous rollout's events cannot satisfy it.
func (o deployObservation) deployedSinceReuse() bool {
	events, _ := o.newEvents()
	for _, e := range events {
		if at, err := time.Parse(time.RFC3339Nano, e.Time); err == nil && strings.EqualFold(e.Status, "DEPLOYED") && at.After(o.reusedAt) {
			return true
		}
	}
	return false
}

// reusedNotice explains an unchanged redeploy. The build cache is shared across
// the workspace, so a reused build alone proves nothing (rolling back to an
// earlier version reuses one too, with a new revision): it is only "unchanged"
// when the revision now deployed already existed before this apply.
func (o deployObservation) reusedNotice() string {
	revision := o.rollout.DeployedRevision
	if o.reusedAt.IsZero() || !o.baseline.known || !o.baseline.includes(revision) {
		return ""
	}
	return fmt.Sprintf("No new revision: the source is unchanged, so the platform reused the identical image build and re-applied revision %s of %s/%s.", revision, o.kind, o.name)
}

// rolloutInProgress reports that the newest event is a rollout step that is not
// the final "deployment.succeeded".
func (o deployObservation) rolloutInProgress() bool {
	event, ok := latestFailureEvent(o.rollout.Events, "")
	return ok && strings.Contains(event.Type, ".deployment.") && !strings.HasSuffix(event.Type, ".succeeded")
}

// buildNotPickedUp reports an uploaded source build that was never answered: no
// build event has appeared since the apply. This is what the platform shows when
// it drops an update, e.g. one submitted while the previous rollout was still in
// flight.
func (o deployObservation) buildNotPickedUp(waited time.Duration) bool {
	events, ok := o.newEvents()
	if !ok || !o.autoGenerated || !o.reusedAt.IsZero() || waited < deployNoBuildGrace {
		return false
	}
	for _, e := range events {
		if isBuildEvent(e) {
			return false
		}
	}
	return true
}
