name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Copy definition
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global url."https://.:${{ secrets.GH_PAT }}@github.com/".insteadOf "https://github.com/"
          git clone https://github.com/${{ github.repository_owner }}/controlplane
          cp controlplane/api/api/definitions/controlplane.yml ./definition.yml
          rm -rf controlplane
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"
          check-latest: true
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: blaxel
          path: dist/*
